apiVersion: batch/v1
kind: Job
metadata:
  name: pipipi
spec:
  template:
    spec:
      containers:
      - name: getnodecurl
        image:  byrnedo/alpine-curl:latest
        command: ["curl"]
        args: 
            - -s
            - 172.22.190.2
      restartPolicy: Never
  backoffLimit: 4
