---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: comment
  namespace: comment
  labels:
    service: comment
    role: proxy
spec:
  routes:
    - services:
        - name: comment
          port: 8080
      conditions:
        - prefix: /comment
      pathRewritePolicy:
        replacePrefix:
          - replacement: /comment
      permitInsecure: true
