---
apiVersion: v1
kind: Secret
metadata:
  name: user-db
  namespace: user
  labels:
    service: user
    role: db
type: Opaque
stringData:
  ROOT_PASSWORD: user
  DATABASE: user
  USER: user
  PASSWORD: user
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-s3-credentials
  namespace: user
  labels:
    service: user
    role: db
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: minio
  AWS_SECRET_ACCESS_KEY: miniosecret
  S3_ENDPOINT: http://minio-hl-svc.infra.svc.cluster.local:9000
---
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: user-db
  namespace: user
  annotations:
    argocd.argoproj.io/hook: Skip
  labels:
    service: user
    role: db
spec:
  replicas: 2
  secretName: user-db
  mysqlVersion: "5.7"
  minAvailable: "10%"

  backupSchedule: "0 0 */2 * *"
  backupURL: s3://user-db/
  backupSecretName: minio-s3-credentials
  backupScheduleJobsHistoryLimit: 3
  backupRemoteDeletePolicy: delete

  podSpec:
    persistentVolumeClaim:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: rook-ceph-block
      resources:
        requests:
          storage: 10Gi
---
