bases:
- ../../manifests/delivery-status/app.yaml
images:
- name: registry-harbor-core.infra.svc.cluster.local/library/delivery-status
  newName: local-delivery-status
patches:
- path: patch-dnspolicy.yaml
  target:
    kind: Deployment
