bases:
- ../../manifests/order/app.yaml
images:
- name: registry-harbor-core.infra.svc.cluster.local/library/order
  newName: local-order
patches:
- path: patch-dnspolicy.yaml
  target:
    kind: Deployment
