# helm2 fetch presslabs/mysql-operator
# helm2 template mysql-operator-0.3.6.tgz --set orchestrator.persistence.storageClass=rook-ceph-block --set installCRDs=true | sed -e 's|RELEASE-NAME-||g' -e 's|release: .*RELEASE-NAME.*||g' -e 's|release-name-||g' -e 's|release: .*release-name.*||g'

---
# Source: mysql-operator/templates/orc-secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: mysql-operator-orc
  namespace: infra
  labels:
    app: mysql-operator
    chart: mysql-operator-0.3.6
    
    heritage: Tiller
data:
  TOPOLOGY_USER: "b3JjaGVzdHJhdG9y"
  TOPOLOGY_PASSWORD: "aEdpU1JOU0hoNA=="

---
# Source: mysql-operator/templates/orc-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-operator-orc
  namespace: infra
  labels:
    app: mysql-operator
    chart: mysql-operator-0.3.6
    
    heritage: Tiller
data:
  orchestrator.conf.json: "{\n  \"ApplyMySQLPromotionAfterMasterFailover\": false,\n  \"BackendDB\": \"sqlite\",\n  \"Debug\": false,\n  \"DetachLostReplicasAfterMasterFailover\": true,\n  \"DetectClusterAliasQuery\": \"SELECT CONCAT(SUBSTRING(@@hostname, 1, LENGTH(@@hostname) - 1 - LENGTH(SUBSTRING_INDEX(@@hostname,'-',-2))),'.',SUBSTRING_INDEX(@@report_host,'.',-1))\",\n  \"DetectInstanceAliasQuery\": \"SELECT @@hostname\",\n  \"DiscoverByShowSlaveHosts\": false,\n  \"FailMasterPromotionIfSQLThreadNotUpToDate\": true,\n  \"HTTPAdvertise\": \"http://{{ .Env.HOSTNAME }}-svc:80\",\n  \"HostnameResolveMethod\": \"none\",\n  \"InstancePollSeconds\": 5,\n  \"ListenAddress\": \":3000\",\n  \"MasterFailoverDetachReplicaMasterHost\": true,\n  \"MySQLHostnameResolveMethod\": \"@@report_host\",\n  \"MySQLTopologyCredentialsConfigFile\": \"/etc/orchestrator/orc-topology.cnf\",\n  \"OnFailureDetectionProcesses\": [\n    \"/usr/local/bin/orc-helper event -w '{failureClusterAlias}' 'OrcFailureDetection' 'Failure: {failureType}, failed host: {failedHost}, lost replcas: {lostReplicas}' || true\",\n    \"/usr/local/bin/orc-helper failover-in-progress '{failureClusterAlias}' '{failureDescription}' || true\"\n  ],\n  \"PostIntermediateMasterFailoverProcesses\": [\n    \"/usr/local/bin/orc-helper event '{failureClusterAlias}' 'OrcPostIntermediateMasterFailover' 'Failure type: {failureType}, failed hosts: {failedHost}, slaves: {countSlaves}' || true\"\n  ],\n  \"PostMasterFailoverProcesses\": [\n    \"/usr/local/bin/orc-helper event '{failureClusterAlias}' 'OrcPostMasterFailover' 'Failure type: {failureType}, new master: {successorHost}, slaves: {slaveHosts}' || true\"\n  ],\n  \"PostUnsuccessfulFailoverProcesses\": [\n    \"/usr/local/bin/orc-helper event -w '{failureClusterAlias}' 'OrcPostUnsuccessfulFailover' 'Failure: {failureType}, failed host: {failedHost} with {countSlaves} slaves' || true\"\n  ],\n  \"PreFailoverProcesses\": [\n    \"/usr/local/bin/orc-helper failover-in-progress '{failureClusterAlias}' '{failureDescription}' || true\"\n  ],\n  \"ProcessesShellCommand\": \"sh\",\n  \"RaftAdvertise\": \"{{ .Env.HOSTNAME }}-svc\",\n  \"RaftBind\": \"{{ .Env.HOSTNAME }}\",\n  \"RaftDataDir\": \"/var/lib/orchestrator\",\n  \"RaftEnabled\": true,\n  \"RaftNodes\": [],\n  \"RecoverIntermediateMasterClusterFilters\": [\n    \".*\"\n  ],\n  \"RecoverMasterClusterFilters\": [\n    \".*\"\n  ],\n  \"RecoveryIgnoreHostnameFilters\": [],\n  \"RecoveryPeriodBlockSeconds\": 300,\n  \"RemoveTextFromHostnameDisplay\": \":3306\",\n  \"SQLite3DataFile\": \"/var/lib/orchestrator/orc.db\",\n  \"SlaveLagQuery\": \"SELECT TIMESTAMPDIFF(SECOND,ts,NOW()) as drift FROM sys_operator.heartbeat ORDER BY drift ASC LIMIT 1\",\n  \"UnseenInstanceForgetHours\": 1\n}"
  orc-topology.cnf: |
    [client]
    user = {{ .Env.ORC_TOPOLOGY_USER }}
    password = {{ .Env.ORC_TOPOLOGY_PASSWORD }}

---
# Source: mysql-operator/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-operator
  namespace: infra
  labels:
    app: mysql-operator
    chart: mysql-operator-0.3.6
    
    heritage: Tiller
---
# Source: mysql-operator/templates/crds.yaml

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    app: 'mysql-operator'
    chart: 'mysql-operator-0.3.6'
    controller-tools.k8s.io: "1.0"
    heritage: 'Tiller'
    
  name: mysqlbackups.mysql.presslabs.org
  annotations:
    helm.sh/hook: crd-install
spec:
  group: mysql.presslabs.org
  names:
    kind: MysqlBackup
    plural: mysqlbackups
  scope: Namespaced
  version: v1alpha1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    app: 'mysql-operator'
    chart: 'mysql-operator-0.3.6'
    controller-tools.k8s.io: "1.0"
    heritage: 'Tiller'
    
  name: mysqlclusters.mysql.presslabs.org
  annotations:
    helm.sh/hook: crd-install
spec:
  additionalPrinterColumns:
  - JSONPath: .status.conditions[?(@.type == "Ready")].status
    description: The cluster status
    name: Ready
    type: string
  - JSONPath: .spec.replicas
    description: The number of desired nodes
    name: Replicas
    type: integer
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: mysql.presslabs.org
  names:
    kind: MysqlCluster
    plural: mysqlclusters
    shortNames:
    - mysql
  scope: Namespaced
  subresources:
    scale:
      specReplicasPath: .spec.replicas
      statusReplicasPath: .status.readyNodes
    status: {}
  version: v1alpha1

---
# Source: mysql-operator/templates/clusterrole.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: 'mysql-operator'
    chart: 'mysql-operator-0.3.6'
    heritage: 'Tiller'
    
  name: 'mysql-operator'
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - mysql.presslabs.org
  resources:
  - mysqlbackups
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - services
  - events
  - jobs
  - pods
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - mysql.presslabs.org
  resources:
  - mysqlclusters
  - mysqlclusters/status
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete

---
# Source: mysql-operator/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: mysql-operator
  labels:
    app: mysql-operator
    chart: mysql-operator-0.3.6
    
    heritage: Tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mysql-operator
subjects:
  - name: mysql-operator
    namespace: infra
    kind: ServiceAccount
---
# Source: mysql-operator/templates/orc-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: mysql-operator-0-svc
  namespace: infra
  labels:
    app: mysql-operator
    chart: mysql-operator-0.3.6
    
    heritage: Tiller
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 80
    targetPort: 3000
  - name: raft
    port: 10008
    targetPort: 10008
  selector:
    statefulset.kubernetes.io/pod-name: mysql-operator-0
---


apiVersion: v1
kind: Service
metadata:
  name: mysql-operator
  namespace: infra
  labels:
    app: mysql-operator
    chart: mysql-operator-0.3.6
    
    heritage: Tiller
spec:
  type: ClusterIP
  selector:
    app: mysql-operator
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000

---
# Source: mysql-operator/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-operator
  namespace: infra
  labels:
    app: mysql-operator
    chart: mysql-operator-0.3.6
    
    heritage: Tiller
spec:
  replicas: 1
  serviceName: mysql-operator-orc
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: mysql-operator
      
  template:
    metadata:
      labels:
        app: mysql-operator
        
      annotations:
        checksum/config: 6a90315df103094b2f29d1020e26239a824cef23f457df1287a4519f90ad765f
        checksum/secret: 650732b32654c4df85d41f487a8915c839e50403ad7b718098b0cf887232b7a3
    spec:
      serviceAccountName: mysql-operator
      containers:
        - name: operator
          image: "quay.io/presslabs/mysql-operator:0.3.6"
          imagePullPolicy: IfNotPresent
          env:
            - name: ORC_TOPOLOGY_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-operator-orc
                  key: TOPOLOGY_USER
            - name: ORC_TOPOLOGY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-operator-orc
                  key: TOPOLOGY_PASSWORD
          args:
            - --leader-election-namespace=infra
            # connect to orchestrator on localhost
            - --orchestrator-uri=http://127.0.0.1:3000/api
            - --sidecar-image=quay.io/presslabs/mysql-operator-sidecar:0.3.6
          resources:
            {}
            
          # TODO: add livenessProbe to controller
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 80
        - name: orchestrator
          image: quay.io/presslabs/mysql-operator-orchestrator:0.3.6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: web
              protocol: TCP
            - containerPort: 10008
              name: raft
              protocol: TCP
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          envFrom:
            - prefix: ORC_
              secretRef:
                name: mysql-operator-orc
          volumeMounts:
            - name: data
              mountPath: /var/lib/orchestrator/
            - name: config
              mountPath: /templates/
          livenessProbe:
            timeoutSeconds: 10
            initialDelaySeconds: 200
            httpGet:
              path: /api/lb-check
              port: 3000
          # https://github.com/github/orchestrator/blob/master/docs/raft.md#proxy-healthy-raft-nodes
          readinessProbe:
            timeoutSeconds: 10
            httpGet:
              path: /api/raft-health
              port: 3000
          resources:
            null
            

      volumes:
        - name: config
          configMap:
            name: mysql-operator-orc

      # security context to mount corectly the volume for orc
      securityContext:
        fsGroup: 777

      affinity:
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ ReadWriteOnce ]
        resources:
          requests:
            storage: 1Gi
        storageClassName: "rook-ceph-block"

---
# Source: mysql-operator/templates/orc-ingress.yaml


---
# Source: mysql-operator/templates/pdb.yaml


---
# Source: mysql-operator/templates/podsecuritypolicy.yaml


---
# Source: mysql-operator/templates/role.yaml


---
# Source: mysql-operator/templates/rolebinding.yaml


