---
apiVersion: v1
kind: ConfigMap
metadata:
  name: check-scripts
  namespace: search
  labels:
    service: search
    role: check
data:
  check.sh: |-
    #!/bin/sh
    echo "check script running..."
    curl -s -u "${DB_USER}:${DB_PASSWORD}" "http://${DB_HOST}:${DB_PORT}"
    curl -s -u "${DB_USER}:${DB_PASSWORD}" "http://${DB_HOST}:${DB_PORT}/_xpack"
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: check-job
  namespace: search
  labels:
    service: search
    role: check
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Replace
  startingDeadlineSeconds: 30
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  suspend: false
  jobTemplate:
    spec:
      completions: 1
      parallelism: 1
      backoffLimit: 10
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: check-container
            image: curlimages/curl:7.69.1
            command:
            - /scripts/check.sh
            env:
            - name: DB_HOST
              value: search-db-es-http.search.svc.cluster.local
            - name: DB_PORT
              value: "9200"
            - name: DB_USER
              value: elastic
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: search-db-es-elastic-user
                  key: elastic
            volumeMounts:
            - name: scripts-volume
              mountPath: /scripts
          volumes:
            - name: scripts-volume
              configMap:
                name: check-scripts
                defaultMode: 493 # mode 755
