---
apiVersion: v1
kind: Secret
metadata:
  name: point-db-credentials
  namespace: point
type: Opaque
stringData:
  DB_NAME: point
  DB_USER: point
  DB_PASSWORD: point
---
apiVersion: yugabytedb.rook.io/v1alpha1
kind: YBCluster
metadata:
  name: point-db
  namespace: point
  annotations:
    argocd.argoproj.io/hook: Skip
spec:
  master:
    # Replica count for Master.
    replicas: 3
    resources:
      requests:
        cpu: 2
        memory: 2Gi
    # Mentioning network ports is optional. If some or all ports are not specified, then they will be defaulted to below-mentioned values, except for tserver-ui.
    network:
      ports:
        - name: yb-master-ui
          port: 7000          # default value
        - name: yb-master-rpc
          port: 7100          # default value
    # Volume claim template for Master
    volumeClaimTemplate:
      metadata:
        name: datadir
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 20Gi
        storageClassName: rook-ceph-block
  tserver:
    # Replica count for TServer
    replicas: 3
    resources:
      requests:
        cpu: 2
        memory: 2Gi
    # Mentioning network ports is optional. If some or all ports are not specified, then they will be defaulted to below-mentioned values, except for tserver-ui.
    # For tserver-ui a cluster ip service will be created if the yb-tserver-ui port is explicitly mentioned. If it is not specified, only StatefulSet & headless service will be created for TServer. TServer ClusterIP service creation will be skipped. Whereas for Master, all 3 kubernetes objects will always be created.
    network:
      ports:
        - name: yb-tserver-ui
          port: 9000
        - name: yb-tserver-rpc
          port: 9100          # default value
        - name: ycql
          port: 9042          # default value
        - name: yedis
          port: 6379          # default value
        - name: ysql
          port: 5433          # default value
    # Volume claim template for TServer
    volumeClaimTemplate:
      metadata:
        name: datadir
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 50Gi
        storageClassName: rook-ceph-block
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-db-script
  namespace: point
  labels:
    service: point
    role: check
data:
  init.sh: |-
    #!/bin/bash
    echo "initialize database running..."
    /home/yugabyte/bin/ysqlsh -h ${DB_HOST} -p ${DB_PORT_YPOSTGRES} -c "CREATE DATABASE ${DB_NAME};"
    /home/yugabyte/bin/ysqlsh -h ${DB_HOST} -p ${DB_PORT_YPOSTGRES} -c "CREATE USER ${DB_USER} WITH PASSWORD '${DB_PASSWORD}';"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: init-db
  namespace: point
  labels:
    service: point
    role: db
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 10000
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: check-container
        image: yugabytedb/yugabyte:2.0.10.0-b4
        command:
        - /scripts/init.sh
        env:
        - name: DB_HOST
          value: yb-tserver-point-db-0.yb-tservers-point-db.point.svc.cluster.local
        - name: DB_PORT_YPOSTGRES
          value: "5433"
        - name: DB_PORT_YCASSANDRA
          value: "9042"
        - name: DB_PORT_YREDIS
          value: "6379"
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: point-db-credentials
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: point-db-credentials
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: point-db-credentials
              key: DB_PASSWORD
        volumeMounts:
        - name: scripts-volume
          mountPath: /scripts
      volumes:
        - name: scripts-volume
          configMap:
            name: init-db-script
            defaultMode: 493 # mode 755
