---
apiVersion: mcrouter.example.com/v1alpha3
kind: Mcrouter
metadata:
  name: point-kvs
  namespace: point
  annotations:
    argocd.argoproj.io/hook: Skip
  labels:
    service: point
    role: kvs
spec:
  memcached_pool_size: 3
  pool_setup: replicated

