bases:
- ../../manifests/user/app.yaml
images:
- name: registry-harbor-core.infra.svc.cluster.local/library/user
  newName: local-user
patches:
- path: patch-dnspolicy.yaml
  target:
    kind: Deployment
