bases:
- ../../manifests/comment/app.yaml
images:
- name: registry-harbor-core.infra.svc.cluster.local/library/comment
  newName: local-comment
patches:
- path: patch-dnspolicy.yaml
  target:
    kind: Deployment
