bases:
- ../../manifests/admin/app.yaml
images:
- name: registry-harbor-core.infra.svc.cluster.local/library/admin
  newName: local-admin
patches:
- path: patch-dnspolicy.yaml
  target:
    kind: Deployment
