apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: point-cd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/__TB_GITHUB_ORG_NAME__/kubernetes-native-testbed.git
    targetRevision: develop
    path: manifests/point
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: point
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

