bases:
- ../../manifests/point/app.yaml
images:
- name: registry-harbor-core.infra.svc.cluster.local/library/point
  newName: local-point
patches:
- path: patch-dnspolicy.yaml
  target:
    kind: Deployment
