bases:
- ../../manifests/search/app.yaml
images:
- name: registry-harbor-core.infra.svc.cluster.local/library/search
  newName: local-search
patches:
- path: patch-dnspolicy.yaml
  target:
    kind: Deployment
