---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: rate
  namespace: rate
  labels:
    service: rate
    role: proxy
spec:
  routes:
    - services:
        - name: rate
          port: 8080
      conditions:
        - prefix: /rate
      pathRewritePolicy:
        replacePrefix:
          - replacement: /rate
      permitInsecure: true
