bases:
- ../../manifests/rate/app.yaml
images:
- name: registry-harbor-core.infra.svc.cluster.local/library/rate
  newName: local-rate
patches:
- path: patch-dnspolicy.yaml
  target:
    kind: Deployment
