---
apiVersion: v1
kind: ConfigMap
metadata:
  name: check-scripts-db
  namespace: order
  labels:
    service: order
    role: check
data:
  check.sh: |-
    #!/bin/bash
    echo "check script running..."
    mysql -u ${DB_USERNAME} -p${DB_PASSWORD} -D ${DB_NAME} -h ${DB_HOST} -P ${DB_PORT} -e "show tables\G"
    mysql -u ${DB_USERNAME} -p${DB_PASSWORD} -D ${DB_NAME} -h ${DB_HOST} -P ${DB_PORT} -e "show databases\G"
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: check-job-db
  namespace: order
  labels:
    service: order
    role: check
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Replace
  startingDeadlineSeconds: 30
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  suspend: false
  jobTemplate:
    spec:
      completions: 1
      parallelism: 1
      backoffLimit: 10
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: check-container
            image: mysql:5.7
            command:
            - /scripts/check.sh
            env:
            - name: DB_HOST
              value: order-db-tidb.order.svc.cluster.local
            - name: DB_PORT
              value: "4000"
            - name: DB_USERNAME
              value: orderuser
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: order-db
                  key: orderuser
            - name: DB_NAME
              value: orderdb
            volumeMounts:
            - name: scripts-volume
              mountPath: /scripts
          volumes:
            - name: scripts-volume
              configMap:
                name: check-scripts-db
                defaultMode: 493 # mode 755
