---
apiVersion: skaffold/v2alpha3
kind: Config
build:
  artifacts:
  - image: local-product
    docker:
      dockerfile: ./product/Dockerfile
    context: ../
  tagPolicy:
    envTemplate:
      template: "local-product:latest"
  local:
    push: false
deploy:
  kustomize:
    paths:
    - ../../development/product
    buildArgs:
    - --load_restrictor
    - LoadRestrictionsNone
    flags:
      delete:
      - --force
      - --grace-period=0
      - --wait
