---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: argocd
  namespace: argocd
  labels:
    service: argocd
    role: proxy
spec:
  routes:
    - services:
        - name: argocd-server
          port: 80
      permitInsecure: true
